In [7]:
import pandas as pd
import requests
from bs4 import BeautifulSoup
import time
import random
from webscraper import *

In [2]:
def get_song_urls_list(url):
    song_urls_list = []

    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')

    for a in soup.find_all('a', {'rel': 'bookmark'}):
        song_urls_list.append(a['href'])
    return song_urls_list


def scrape_first_page(start_url, empty_df):
    
    start_urls_list = get_song_urls_list(start_url)
    z = 1
    for url in start_urls_list:
        print(f'starting song: {z}')
        print(url)
        z+=1
        
        r = requests.get(url)
        soup = BeautifulSoup(r.text, 'html.parser')
        tags = soup.find_all(['td','p'])
        td_tags = soup.find_all(['td'])
        p_tags = soup.find_all(['p'])
        
        kor = pd.DataFrame()
        eng = pd.DataFrame()

        if (td_tags[-1].text=='N/A') | (td_tags[-1].text=='soon') | (td_tags[-1].text=='Coming Soon!') | (len(tags)<25) | (p_tags[-3].text[0:6]!='Korean'):
            time.sleep(random.randint(5,8))
            continue
        else:
            c = len(tags) - 3
            d = c - 7
            e = int(d/3)
            a = e + 7
            b = e + a

            for i in range(a,b):
                kor_lines = tags[i]
                kor_lines_series = pd.Series(kor_lines.text.split('\n'))
                kor = pd.concat([kor, kor_lines_series])
                kor = kor[kor[0]!=""]
            kor = kor.rename(columns={0:'kor'})

            for i in range(b,c):
                eng_lines = tags[i]
                eng_lines_series = pd.Series(eng_lines.text.split('\n'))
                eng = pd.concat([eng, eng_lines_series])
                eng = eng[eng[0]!=""]
            eng = eng.rename(columns={0:'eng'})
            
            if eng.shape != kor.shape:
                time.sleep(random.randint(5,8))
                continue
            else:
                concatted = pd.concat([eng, kor],axis=1)
                concatted = concatted.drop_duplicates()
                concatted = concatted.query("eng != kor")

                empty_df = pd.concat([empty_df,concatted])

                time.sleep(random.randint(6,9))
    return empty_df


def scrape_it(start_url, empty_df, end):
    
    z=1
    print(f'Starting page: {z}')
    df = scrape_first_page(start_url, empty_df)
    
    for i in range(99,end+1):
        
        z+=1
        print(f'Starting page: {z}')
        next_url = f'https://colorcodedlyrics.com/category/krn/page/{i}'

        urls_list = get_song_urls_list(next_url)
        if (i==100) | (i==200) | (i==300) | (i==400) | (i==500) | (i==600) | (i==700):
            df.to_csv('lyrics_save{}.csv'.format(i), sep='\t')
            df.to_csv('lyrics_save{}.txt'.format(i), sep='\t')
            print(f'saved up tp page: {i}')

        for url in urls_list:

            r = requests.get(url)
            soup = BeautifulSoup(r.text, 'html.parser')
            tags = soup.find_all(['td','p'])
            td_tags = soup.find_all(['td'])
            p_tags = soup.find_all(['p'])
            
            kor = pd.DataFrame()
            eng = pd.DataFrame()

            if (td_tags[-1].text=='N/A') | (td_tags[-1].text=='soon') | (td_tags[-1].text=='Coming Soon!') | (len(tags)<25) | (p_tags[-3].text[0:6]!='Korean'):
                time.sleep(random.randint(5,8))
                continue
            else:
                c = len(tags) - 3
                d = c - 7
                e = int(d/3)
                a = e + 7
                b = e + a

                for i in range(a,b):
                    kor_lines = tags[i]
                    kor_lines_series = pd.Series(kor_lines.text.split('\n'))
                    kor = pd.concat([kor, kor_lines_series])
                    kor = kor[kor[0]!=""]
                kor = kor.rename(columns={0:'kor'})

                for i in range(b,c):
                    eng_lines = tags[i]
                    eng_lines_series = pd.Series(eng_lines.text.split('\n'))
                    eng = pd.concat([eng, eng_lines_series])
                    eng = eng[eng[0]!=""]
                eng = eng.rename(columns={0:'eng'})

                if eng.shape != kor.shape:
                    time.sleep(random.randint(5,8))
                    continue
                else:
                    concatted = pd.concat([eng, kor],axis=1)
                    concatted = concatted.drop_duplicates()
                    concatted = concatted.query("eng != kor")

                    df = pd.concat([df,concatted])

                    time.sleep(random.randint(5,8))

        
    return df

In [15]:
url = 'https://colorcodedlyrics.com/category/krn/page/101'
empty = pd.DataFrame(columns = ['eng','kor'])
df = scrape_first_page(start_url=url, empty_df=empty)

starting song: 1
https://colorcodedlyrics.com/2019/03/stray-kids-chronosaurus
starting song: 2
https://colorcodedlyrics.com/2019/03/stray-kids-boxer
starting song: 3
https://colorcodedlyrics.com/2019/03/stray-kids-maze-of-memories-jamgganui-goyo
starting song: 4
https://colorcodedlyrics.com/2019/03/stray-kids-victory-song-seungjeonga
starting song: 5
https://colorcodedlyrics.com/2019/03/momoland-what-you-want
starting song: 6
https://colorcodedlyrics.com/2019/03/momoland-holiday
starting song: 7
https://colorcodedlyrics.com/2019/03/momoland-light-up-bichna

ValueError: Shape of passed values is (755, 2), indices imply (73, 2)

In [7]:
url = 'https://colorcodedlyrics.com/2019/03/momoland-light-up-bichna'

r = requests.get(url)
soup = BeautifulSoup(r.text, 'html.parser')
tags = soup.find_all(['td','p'])
td_tags = soup.find_all(['td'])
p_tags = soup.find_all(['p'])

In [9]:
kor = pd.DataFrame()
eng = pd.DataFrame()

c = len(tags) - 3
d = c - 7
e = int(d/3)
a = e + 7
b = e + a

for i in range(a,b):
    kor_lines = tags[i]
    kor_lines_series = pd.Series(kor_lines.text.split('\n'))
    kor = pd.concat([kor, kor_lines_series])
    kor = kor[kor[0]!=""]
kor = kor.rename(columns={0:'kor'})

for i in range(b,c):
    eng_lines = tags[i]
    eng_lines_series = pd.Series(eng_lines.text.split('\n'))
    eng = pd.concat([eng, eng_lines_series])
    eng = eng[eng[0]!=""]
eng = eng.rename(columns={0:'eng'})

In [10]:
kor

                                 kor
0       Who else could do it better?
1             Uha uha nobody but me!
0   빛나! 저 태양처럼(just do it like this)
1   Only one 내가 되고 싶어(nobody but me)
2   빛나! 저 태양처럼(just do it like this)
..                               ...
0   빛나! 저 태양처럼(just do it like this)
1   Only one 내가 되고 싶어(nobody but me)
2   빛나! 저 태양처럼(just do it like this)
3                  날 믿어 get a chance
4                     우리 아님 누가 lucky

[73 rows x 1 columns]

In [11]:
eng

                                            eng
0                  Who else could do it better?
1                        Uha uha nobody but me!
0   I shine like the sun (Just do it like this)
1     Only one, I want to be me (Nobody but me)
2   I shine like the sun (Just do it like this)
..                                          ...
0   I shine like the sun (Just do it like this)
1     Only one, I want to be me (Nobody but me)
2   I shine like the sun (Just do it like this)
3                   Believe in me, get a chance
4                     Who would shine if not us

[73 rows x 1 columns]

In [40]:
url = 'https://colorcodedlyrics.com/2019/03/momoland-light-up-bichna'
r = requests.get(url)
soup = BeautifulSoup(r.text, 'html.parser')
tags = soup.find_all(['td','p'])
td_tags = soup.find_all(['td'])
p_tags = soup.find_all(['p'])

kor = pd.DataFrame()
eng = pd.DataFrame()
df = pd.DataFrame(columns = ['eng','kor'])

c = len(tags) - 3
d = c - 7
e = int(d/3)
a = e + 7
b = e + a

for i in range(a,b):
    kor_lines = tags[i]
    kor_lines_series = pd.Series(kor_lines.text.split('\n'))
    kor = pd.concat([kor, kor_lines_series])
    kor = kor[kor[0]!=""]
kor = kor.rename(columns={0:'kor'}).reset_index().drop(columns='index')

for i in range(b,c):
    eng_lines = tags[i]
    eng_lines_series = pd.Series(eng_lines.text.split('\n'))
    eng = pd.concat([eng, eng_lines_series])
    eng = eng[eng[0]!=""]
eng = eng.rename(columns={0:'eng'}).reset_index().drop(columns='index')

# if eng.shape != kor.shape:
#     time.sleep(random.randint(5,8))
#     continue
# else:
concatted = pd.concat([eng, kor],axis=1)
concatted = concatted.drop_duplicates()
concatted = concatted.query("eng != kor")

df = pd.concat([df,concatted])

# time.sleep(random.randint(5,8))

In [41]:
df

,eng,kor
2,I shine like the sun (Just do it like this),빛나! 저 태양처럼(just do it like this)
3,"Only one, I want to be me (Nobody but me)",Only one 내가 되고 싶어(nobody but me)
5,"Believe in me, get a chance",날 믿어 get a chance
6,Who would shine if not us,우리 아님 누가 빛나
7,"Good luck follows me, everyone is gathering",행운 follow me 모두 gathering
8,"Even further, gathering wordwide",더 멀리 world wide 까지 gathering
9,"You have too much confidence, who do you think...",뭘 믿고 자신감 too much
10,"Everyone asks me, but I just do it",묻는데 나 just do it
11,"Nobody, not anyone",nobody 그 누구도
12,Can replace me,대체 할 수 없어
13,"Someone like that doesn’t exist, because",어디 없어 왜냐면
14,"I choose my own path, baby",내 길 내가 결정해 baby
15,I don’t want to follow,가고 싶진 않아
16,Other people too far,남 따라 저 멀리
17,I want to live trying everything I can do,할 수 있는 모든 건 다 해보면서 살래
18,Just be who I am,just 나답게
19,Who would make it if not me,나 아님 누가 make it
20,Tomorrow is unknown,내일을 알 순 없어
21,"No wait, I’m choosing my path now",No wait 내 길 now 선택해
22,I’ll make every day,매일을 전부 make it
23,The super duper lucky that came to me,내게 온 super duper lucky
24,Lucky,(lucky~)
25,"Get ready, I’m ready",Get ready 준비 됐어.
26,I’ll show you my everything,보여 줄 내 전부를
33,"Sing a song, na na na na",Sing a song 나나나나
34,Someone be happy,누군가 be happy
35,Like that bright sun,눈부신 저 태양처럼
36,I’ll become your light,네게 빛이 될게
37,It seems like you’ll fail but you succeed,안되다가도 돼
38,It seems like you’ll succeed but you fail,되다가도 fail
39,"Don’t mind it too much, what does it matter",신경쓰지 마 좀 뭐 어때
40,I’ll be by your side,곁에 있을게
41,I’ll sing a song for you,너 위한 노랠 부를게
42,You can trust me and follow me,날 믿고 따라 와도 돼
43,The future is unknown,미래를 알 순 없어
44,"No way, I’m choosing my path now",No way 내 길 now 선택해
45,I’ll make everything I have,내 모두를 전부 make it
48,"Get ready, I’m ready",Get ready 준비 됐어
61,"Sing along to my song, baby",내 노래 따라 불러줘 baby
62,Super lucky,super lucky
63,This moment is the best,최고의 이순간을
65,There is no place where it can’t be heard,안 들리는 데가 없어
66,"Believe me, get a chance",믿어 get a chance
67,Who is lucky if not us,우리 아님 누가 lucky
72,Who would shine if not us,우리 아님 누가 lucky

In [27]:
eng.shape

(73, 1)

In [28]:
kor.shape

(73, 1)

In [30]:
eng

                                            eng
0                  Who else could do it better?
1                        Uha uha nobody but me!
0   I shine like the sun (Just do it like this)
1     Only one, I want to be me (Nobody but me)
2   I shine like the sun (Just do it like this)
..                                          ...
0   I shine like the sun (Just do it like this)
1     Only one, I want to be me (Nobody but me)
2   I shine like the sun (Just do it like this)
3                   Believe in me, get a chance
4                     Who would shine if not us

[73 rows x 1 columns]

In [31]:
kor

                                 kor
0       Who else could do it better?
1             Uha uha nobody but me!
0   빛나! 저 태양처럼(just do it like this)
1   Only one 내가 되고 싶어(nobody but me)
2   빛나! 저 태양처럼(just do it like this)
..                               ...
0   빛나! 저 태양처럼(just do it like this)
1   Only one 내가 되고 싶어(nobody but me)
2   빛나! 저 태양처럼(just do it like this)
3                  날 믿어 get a chance
4                     우리 아님 누가 lucky

[73 rows x 1 columns]

In [2]:
start_url = 'https://colorcodedlyrics.com/category/krn'

empty = pd.DataFrame(columns = ['eng','kor'])

df = scrape_it(start_url=start_url, empty_df=empty, end=3)

Starting page: 1
Starting page: 2
Starting page: 3

In [3]:
url = ['https://colorcodedlyrics.com/2019/08/content-survey','https://colorcodedlyrics.com/2019/08/up10tion-your-gravity']
for i in url:
    r = requests.get(url)
    soup = BeautifulSoup(r.text, 'html.parser')
    tags = soup.find_all(['td','p'])
    td_tags = soup.find_all(['td'])
    p_tags = soup.find_all(['p'])
    
    if

In [6]:
len(td_tags)

0

In [5]:
p_tags[-3].text[0:6]

'Which '

In [ ]:
kor = pd.DataFrame()
eng = pd.DataFrame()
df = pd.DataFrame(columns = ['eng','kor'])

c = len(tags) - 3
d = c - 7
e = int(d/3)
a = e + 7
b = e + a

for i in range(a,b):
    kor_lines = tags[i]
    kor_lines_series = pd.Series(kor_lines.text.split('\n'))
    kor = pd.concat([kor, kor_lines_series])
    kor = kor[kor[0]!=""]
kor = kor.rename(columns={0:'kor'}).reset_index().drop(columns='index')

for i in range(b,c):
    eng_lines = tags[i]
    eng_lines_series = pd.Series(eng_lines.text.split('\n'))
    eng = pd.concat([eng, eng_lines_series])
    eng = eng[eng[0]!=""]
eng = eng.rename(columns={0:'eng'}).reset_index().drop(columns='index')

# if eng.shape != kor.shape:
#     time.sleep(random.randint(5,8))
#     continue
# else:
concatted = pd.concat([eng, kor],axis=1)
concatted = concatted.drop_duplicates()
concatted = concatted.query("eng != kor")

df = pd.concat([df,concatted])

# time.sleep(random.randint(5,8))